spring:
    application:
        name: explore-spring-batch-multi-datasource
    jpa:
        database: default
        show-sql: true
        open-in-view: false
        hibernate.ddl-auto: validate
        properties.hibernate:
            format_sql: false
            jdbc.time_zone: UTC
            generate_statistics: false
            jdbc.batch_size: ${DB_BATCH_SIZE}
            connection:
                provider_disables_autocommit: true
    datasource:
        url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}?currentSchema=${DB_SCHEMA}
        username: ${DB_USER}
        password: ${DB_PASSWORD}
        driver-class-name: org.postgresql.Driver
        hikari:
            auto-commit: false
            continue-on-error: true
            connection-timeout: ${DB_CONNECTION_TIMEOUT}
            idle-timeout: ${DB_IDLE_TIMEOUT}
            minimum-idle: ${DB_MINIMUM_IDLE}
            max-lifetime: ${DB_MAX_LIFETIME}
            maximum-pool-size: ${DB_MAXIMUM_POOL_SIZE}
            connection-test-query: SELECT 1
            validation-interval: 5000
            pool-name: HikariPool-Domain
